### ISSUE TITLE
No Email set

### ISSUE THREAD

**Issue by rmcgirr83** [ForumHulp/adduser#1]
Email address isn't set and no email is sent to the user that is added.  Not sure what the purpose of this mod is other than adding fake users?

**Comment by ForumHulp** [comment]
Nobody said this extension will send a email to a new user. It can't because the email address isn't set yet. thinking of this is for adding fake users is for admins not worth to be a forum owner. When changing a user's password phpbb also don't send a email to the user.

**Comment by rmcgirr83** [comment]
Then enlighten me as to what the purpose of the extension is?  As the user is not notified that an account has been created.  Is it then up to the admin to send an email to the user that was added?  It is then up to the admin to edit the newly made user to insert an email address?

When changing a users password phpBB may not send an email, don't know haven't tried it in a while, but it does require one to know what the email address is as well as what the user name is.  At least that is the way it works in 3.0.x.  In the 3.0.x mod the admin can set an email address as well as a password if they so choose.

Further if you can't take criticism then "it is not worth to be an extension writer" to use your example. 

Anyway, I was just giving some insight for others for this mod.  I didn't install it but simply looked at the code.  Do with it as you will.

**Comment by ForumHulp** [comment]
Ever thought of intranet users or a small company without a mail address for everyone?

**Comment by rmcgirr83** [comment]
Just about every intranet small or large company has email addresses for it's employees and I very highly doubt that the main use of phpBB would be for intranet or business use.  Using your logic how would an employee of a small company reset their password without an email?  They would have to contact the admin of the small company phpBB forum.  Many businesses do not allow the companies browser to allow the use of remember me type settings in browsers for their employees (this can be set via a GPO using Small Business Server).

I am a CFO for a small company and all management employees have an email address.

Frankly I don't care about this mod.  I was offering a suggestion.  You can choose to consider it or continue to bash me about it.  Matters not one iota to me either way.  I'll just port the 3.0.x mod once 3.1 goes gold.

**Comment by ForumHulp** [comment]
Hi Richard, the world has many forms and I'm not bashing you. 
You asked a question and I answered it and like this extension is working it's not possible to send a email if you looked at it's working. 
There are many companies without a mail for every employee and phpbb is used as a kb under employees. They simply contact the admin, mostly another employee for a reset. 
Of course you can port your mod, why not.
As the phpbb team rejected the event for making this work, it's necessary to change the core always.
